(function(g){var window=this;'use strict';var LXa=function(a,b){a.Ma("onAutonavCoundownStarted",b)},N5=function(a,b,c){g.N(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Re(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.RE&&(b.lengthText?(e=b.lengthText||null,f=b.Dq||null):b.lengthSeconds&&(e=g.cL(b.lengthSeconds),f=g.cL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.NE(d).type;var l=b instanceof g.RE?b.isLivePlayback:null,m=b instanceof g.RE?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.Vl||g.nH("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.al(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Cn};b instanceof g.QE&&(c.playlist_length=b.playlistLength);a.update(c)},O5=function(a){var b=a.U(),c=b.i;
g.V.call(this,{D:"a",K:"ytp-autonav-suggestion-card",V:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{D:"div",Fa:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],V:{style:"{{background}}"},T:[{D:"div",V:{"aria-label":"{{timestamp}}"},Fa:["ytp-autonav-timestamp"],ea:"{{duration}}"},{D:"div",Fa:["ytp-autonav-live-stamp"],ea:"Live"},{D:"div",
Fa:["ytp-autonav-upcoming-stamp"],ea:"Upcoming"},{D:"div",K:"ytp-autonav-list-overlay",T:[{D:"div",K:"ytp-autonav-mix-text",ea:"Mix"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",Fa:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ea:"{{title}}"},{D:"div",Fa:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ea:"{{author}}"},{D:"div",Fa:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ea:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.i=c;this.Oa("click",this.onClick);this.Oa("keypress",this.onKeyPress)},Q5=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-container"});var c=this;this.I=b;this.C=void 0;this.j=0;b=a.U();var d=b.i;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);this.i=new g.V({D:"div",K:"ytp-autonav-endscreen-upnext-container",V:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{D:"div",
K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",ea:"{{autoplayAlternativeHeader}}"},{D:"a",K:"ytp-autonav-endscreen-link-container",V:{href:"{{url}}",target:d?b.J:""},T:[{D:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",V:{style:"{{background}}"},T:[{D:"div",V:{"aria-label":"{{timestamp}}"},Fa:["ytp-autonav-timestamp"],ea:"{{duration}}"},{D:"div",Fa:["ytp-autonav-live-stamp"],ea:"Live"},{D:"div",Fa:["ytp-autonav-upcoming-stamp"],ea:"Upcoming"}]},
{D:"div",K:"ytp-autonav-endscreen-video-info",T:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",ea:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",ea:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",ea:"{{views_and_publish_time}}"},{D:"div",K:"ytp-autonav-author-and-view",ea:"{{author_and_views}}"}]}]}]});g.I(this,this.i);this.i.Aa(this.element);d||this.S(this.i.Ca("ytp-autonav-endscreen-link-container"),"click",this.DJ);this.G.Ab(this.element,
this,115127);this.G.Ab(this.i.Ca("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({D:"div",K:"ytp-autonav-overlay"});g.I(this,this.overlay);this.overlay.Aa(this.element);this.u=new g.V({D:"div",K:"ytp-autonav-endscreen-button-container"});g.I(this,this.u);this.u.Aa(this.element);this.cancelButton=new g.V({D:"button",Fa:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],V:{"aria-label":"Cancel autoplay"},ea:"Cancel"});g.I(this,this.cancelButton);
this.cancelButton.Aa(this.u.element);this.cancelButton.Oa("click",this.KR,this);this.G.Ab(this.cancelButton.element,this,115129);this.playButton=new g.V({D:"a",Fa:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],V:{href:"{{url}}",role:"button","aria-label":"Play next video"},ea:"Play Now"});g.I(this,this.playButton);this.playButton.Aa(this.u.element);this.playButton.Oa("click",this.DJ,this);this.G.Ab(this.playButton.element,this,115130);this.B=new g.J(function(){P5(c)},
500);
g.I(this,this.B);this.CJ();this.S(a,"autonavvisibility",this.CJ)},T5=function(a){var b=a.G.Fj(!0,a.G.isFullscreen());
g.N(a.element,"ytp-autonav-endscreen-small-mode",a.Af(b));g.N(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.cC);g.N(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.pe());g.N(a.G.getRootNode(),"countdown-running",a.Mh());g.N(a.element,"ytp-player-content",a.G.pe());g.yn(a.overlay.element,{width:b.width+"px"});if(!a.Mh()){a.G.pe()?R5(a,Math.round(S5(a)/1E3)):R5(a);b=!!a.suggestion&&!!a.suggestion.Cn;var c=a.G.pe()||!b;g.N(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.N(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.dK(a.u,a.G.pe())}},P5=function(a){var b=S5(a),c=Math,d=c.min;
var e=a.j?Date.now()-a.j:0;c=d.call(c,e,b);R5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Mh()?a.select(!0):a.Mh()&&a.B.start()},S5=function(a){var b=a.G.gq();
return 0<=b?b:g.SC(a.G.U().experiments,"autoplay_time")||1E4},R5=function(a,b){b=void 0===b?-1:b;
a=a.i.Ca("ytp-autonav-endscreen-upnext-header");g.Th(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Sh("Up next in $SECONDS".slice(0,d)));var e=g.Rh("span");g.fq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Yh(e,b);a.appendChild(e);a.appendChild(g.Sh("Up next in $SECONDS".slice(d+c.length)));return}}g.Yh(a,"Up next")},U5=function(a,b){g.V.call(this,{D:"div",
Fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},V5=function(a){g.V.call(this,{D:"div",
Fa:["ytp-upnext","ytp-player-content"],V:{"aria-label":"{{aria_label}}"},T:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",V:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",T:[{D:"span",K:"ytp-upnext-header",ea:"Up Next"},{D:"span",K:"ytp-upnext-title",ea:"{{title}}"},{D:"span",K:"ytp-upnext-author",ea:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",V:{role:"button",href:"{{url}}","aria-label":"Play next video"},T:[{D:"svg",V:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
T:[{D:"circle",K:"ytp-svg-autoplay-circle",V:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",V:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",V:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",T:[{D:"span",K:"ytp-upnext-cancel"},{D:"span",K:"ytp-upnext-paused",
ea:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.C=this.Ca("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.J(this.Dz,5E3,this);this.j=0;var b=this.Ca("ytp-upnext-cancel");this.cancelButton=new g.V({D:"button",Fa:["ytp-upnext-cancel-button","ytp-button"],V:{tabindex:"0","aria-label":"Cancel autoplay"},ea:"Cancel"});g.I(this,this.cancelButton);this.cancelButton.Oa("click",this.LR,this);this.cancelButton.Aa(b);this.cancelButton&&this.api.Ab(this.cancelButton.element,
this,115129);g.I(this,this.B);this.api.Ab(this.element,this,18788);b=this.Ca("ytp-upnext-autoplay-icon");this.S(b,"click",this.MR);this.api.Ab(b,this,115130);this.EJ();this.S(a,"autonavvisibility",this.EJ);this.S(a,"mdxnowautoplaying",this.wW);this.S(a,"mdxautoplaycanceled",this.xW);g.N(this.element,"ytp-upnext-mobile",this.api.U().isMobile)},MXa=function(a,b){return b?b:0<=a.api.gq()?a.api.gq():g.SC(a.api.U().experiments,"autoplay_time")||1E4},W5=function(a,b){b=MXa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.j;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.C.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Mh()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Mh()&&a.i.start()},X5=function(a){U5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({D:"div",K:"ytp-suggestion-panel",T:[{D:"div",Fa:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ea:"More videos"}]});this.J=new g.V({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.I=!1;this.j=new Q5(this.player);g.I(this,this.j);this.j.Aa(this.element);a.getVideoData().uc?this.i=this.j:(this.i=new V5(a),g.VM(this.player,this.i.element,4),g.I(this,this.i));this.overlay=new g.V({D:"div",
K:"ytp-autonav-overlay-cancelled-state"});g.I(this,this.overlay);this.overlay.Aa(this.element);this.B=new g.ZB(this);g.I(this,this.B);g.I(this,this.table);this.table.Aa(this.element);this.table.show();g.I(this,this.J);this.J.Aa(this.table.element);this.hide()},Y5=function(a){var b=a.pe();
b!==a.C&&(a.C=b,a.player.Z("autonavvisibility"),a.C?(a.j!==a.i&&a.j.hide(),a.table.hide()):(a.j!==a.i&&a.j.show(),a.table.show()))},Z5=function(a){U5.call(this,a,"subscribecard-endscreen");
this.i=new g.V({D:"div",K:"ytp-subscribe-card",T:[{D:"img",K:"ytp-author-image",V:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",T:[{D:"div",K:"ytp-author-name",ea:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.I(this,this.i);this.i.Aa(this.element);var b=a.getVideoData();this.subscribeButton=new g.nO("Subscribe",null,"Unsubscribe",null,!0,!1,b.pj,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.subscribeButton);this.subscribeButton.Aa(this.i.Ca("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.Ia);this.Ia();this.hide()},$5=function(a){var b=a.U(),c=g.gz||g.WD?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",Fa:e,V:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},T:[{D:"div",K:"ytp-videowall-still-image",V:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",T:[{D:"span",K:"ytp-videowall-still-info-bg",T:[{D:"span",K:"ytp-videowall-still-info-content",V:c,T:[{D:"span",K:"ytp-videowall-still-info-title",ea:"{{title}}"},{D:"span",
K:"ytp-videowall-still-info-author",ea:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",ea:"Live"},{D:"span",K:"ytp-videowall-still-info-duration",ea:"{{duration}}"}]}]}]},{D:"span",Fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],T:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",K:"ytp-videowall-still-listlabel-length",T:[" (",{D:"span",ea:"{{playlist_length}}"},")"]}]},{D:"span",Fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
T:[{D:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",K:"ytp-videowall-still-listlabel-length",ea:" (50+)"}]}]});this.suggestion=null;this.j=d;this.api=a;this.i=new g.ZB(this);g.I(this,this.i);this.Oa("click",this.onClick);this.Oa("keypress",this.onKeyPress);this.i.S(a,"videodatachange",this.onVideoDataChange);a.Vg(this.element,this);this.onVideoDataChange()},a6=function(a){U5.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.u=0;this.stills=[];this.B=this.videoData=null;this.C=this.J=!1;this.N=null;this.j=new g.ZB(this);g.I(this,this.j);this.I=new g.J(function(){g.K(b.element,"ytp-show-tiles")},0);
g.I(this,this.I);var c=new g.V({D:"button",Fa:["ytp-button","ytp-endscreen-previous"],V:{"aria-label":"Previous"},T:[g.iK()]});g.I(this,c);c.Aa(this.element);c.Oa("click",this.QR,this);this.table=new g.aK({D:"div",K:"ytp-endscreen-content"});g.I(this,this.table);this.table.Aa(this.element);c=new g.V({D:"button",Fa:["ytp-button","ytp-endscreen-next"],V:{"aria-label":"Next"},T:[g.jK()]});g.I(this,c);c.Aa(this.element);c.Oa("click",this.PR,this);a.getVideoData().uc?this.i=new Q5(a,!0):this.i=new V5(a);
g.I(this,this.i);g.VM(this.player,this.i.element,4);this.hide()},b6=function(a){return g.WM(a.player)&&a.Jv()&&!a.B},c6=function(a){var b=a.pe();
b!==a.J&&(a.J=b,a.player.Z("autonavvisibility"))},d6=function(a){g.iN.call(this,a);
var b=this;this.endScreen=null;this.i=this.j=this.u=!1;this.listeners=new g.ZB(this);g.I(this,this.listeners);this.env=a.U();NXa(a)?(this.u=!0,OXa(this),this.i?this.endScreen=new X5(a):this.endScreen=new a6(this.player)):this.env.ke?this.endScreen=new Z5(this.player):this.endScreen=new U5(this.player);g.I(this,this.endScreen);g.VM(this.player,this.endScreen.element,4);PXa(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.Zx("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.S(a,g.$x("endscreen"),function(c){b.onCueRangeExit(c)})},OXa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Ji&&a.j===b.uc)return!1;a.i=b.Ji;a.j=b.uc;return!0},NXa=function(a){a=a.U();
return!a.N&&a.Ob&&!a.ke},PXa=function(a){a.player.gf("endscreen");
var b=a.player.getVideoData();b=new g.Xx(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Xx(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Md([b,c])};
g.OM.prototype.gq=g.ca(4,function(){return this.app.gq()});
g.JX.prototype.gq=g.ca(3,function(){return this.getVideoData().OO});g.v(O5,g.V);O5.prototype.select=function(){(this.G.jk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.dw||void 0)||this.G.L("web_player_endscreen_double_log_fix_killswitch"))&&this.G.vb(this.element)};
O5.prototype.onClick=function(a){g.HN(a,this.G,this.i,this.suggestion.sessionData||void 0)&&this.select()};
O5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.It(a)||(this.select(),g.Ht(a))}};g.v(Q5,g.V);g.k=Q5.prototype;g.k.bz=function(a){this.suggestion!==a&&(this.suggestion=a,N5(this.i,a),this.playButton.La("url",this.suggestion.al()),T5(this))};
g.k.Mh=function(){return 0<this.j};
g.k.uu=function(){this.Mh()||(this.j=Date.now(),P5(this),LXa(this.G,S5(this)),g.N(this.G.getRootNode(),"countdown-running",this.Mh()))};
g.k.Oq=function(){this.dn();P5(this);var a=this.i.Ca("ytp-autonav-endscreen-upnext-header");a&&g.Yh(a,"Up next")};
g.k.dn=function(){this.Mh()&&(this.B.stop(),this.j=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.dn()};
g.k.DJ=function(a){g.HN(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.vb(this.playButton.element):a.currentTarget===this.i.Ca("ytp-autonav-endscreen-link-container")&&(a=this.i.Ca("ytp-autonav-endscreen-link-container"),this.G.bb(a,!0),this.G.vb(a)),this.select())};
g.k.KR=function(){this.G.vb(this.cancelButton.element);g.QM(this.G,!0);this.C&&this.G.Ma("innertubeCommand",this.C)};
g.k.onVideoDataChange=function(a,b){a=b.VZ;this.C=null===a||void 0===a?void 0:a.command};
g.k.CJ=function(){var a=this.G.pe();this.I&&this.rb!==a&&g.dK(this,a);T5(this);this.G.bb(this.element,a);this.G.bb(this.cancelButton.element,a);this.G.bb(this.i.Ca("ytp-autonav-endscreen-link-container"),a);this.G.bb(this.playButton.element,a)};
g.k.Af=function(a){return 400>a.width||459>a.height};g.v(U5,g.V);g.k=U5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Jv=function(){return!1};
g.k.pe=function(){return!1};
g.k.HM=function(){return!1};g.v(V5,g.V);g.k=V5.prototype;g.k.Dz=function(){this.notification&&(this.B.stop(),this.vc(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.bz=function(a){this.suggestion=a;N5(this,a,"hqdefault.jpg")};
g.k.EJ=function(){g.dK(this,this.api.pe());this.api.bb(this.element,this.api.pe());this.api.bb(this.Ca("ytp-upnext-autoplay-icon"),this.api.pe());this.cancelButton&&this.api.bb(this.cancelButton.element,this.api.pe())};
g.k.HW=function(){window.focus();this.Dz()};
g.k.uu=function(a){var b=this;this.Mh()||(g.Xt("a11y-announce","Up Next "+this.suggestion.title),this.j=(0,g.Q)(),this.i=new g.J(function(){W5(b,a)},25),W5(this,a),LXa(this.api,MXa(this,a)));
g.iq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Mh=function(){return!!this.i};
g.k.Oq=function(){this.dn();this.j=(0,g.Q)();W5(this);g.K(this.element,"ytp-upnext-autoplay-paused")};
g.k.dn=function(){this.Mh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.Dz(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Re()}),this.u=this.S(this.notification,"click",this.HW),this.B.start())}this.dn();this.api.nextVideo(!1,a)};
g.k.MR=function(a){!g.Xh(this.cancelButton.element,g.Dt(a))&&g.HN(a,this.api)&&(this.api.pe()&&this.api.vb(this.Ca("ytp-upnext-autoplay-icon")),this.select())};
g.k.LR=function(){this.api.pe()&&this.cancelButton&&this.api.vb(this.cancelButton.element);g.QM(this.api,!0)};
g.k.wW=function(a){this.api.getPresentingPlayerType();this.show();this.uu(a)};
g.k.xW=function(){this.api.getPresentingPlayerType();this.dn();this.hide()};
g.k.ra=function(){this.dn();this.Dz();g.V.prototype.ra.call(this)};g.v(X5,U5);g.k=X5.prototype;g.k.create=function(){U5.prototype.create.call(this);this.B.S(this.player,"appresize",this.uv);this.B.S(this.player,"onVideoAreaChange",this.uv);this.B.S(this.player,"videodatachange",this.onVideoDataChange);this.B.S(this.player,"autonavchange",this.FJ);this.B.S(this.player,"autonavcancel",this.NR);this.onVideoDataChange()};
g.k.show=function(){U5.prototype.show.call(this);(this.I||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.QM(this.player,!1);g.WM(this.player)&&this.Jv()&&!this.u?(Y5(this),2===this.videoData.autonavState?this.player.U().L("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.uu():3===this.videoData.autonavState&&this.i.Oq()):(g.QM(this.player,!0),Y5(this));this.uv()};
g.k.hide=function(){U5.prototype.hide.call(this);this.i.Oq();Y5(this)};
g.k.uv=function(){var a=this.player.Fj(!0,this.player.isFullscreen());Y5(this);T5(this.j);g.N(this.element,"ytp-autonav-cancelled-small-mode",this.Af(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.IA(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.yn(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.q(b.value);b=c.next().value;c=c.next().value;g.N(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.i.bz(a[0]);this.i!==this.j&&this.j.bz(a[0]);for(var b=0;b<QXa.length;++b){var c=QXa[b];if(a&&a[c]){this.videos[b]=new O5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,N5(d,c));g.I(this,this.videos[b]);this.videos[b].Aa(this.J.element)}}}this.uv()}};
g.k.FJ=function(a){1===a?(this.I=!1,this.u=this.videoData.clientPlaybackNonce,this.i.dn(),this.rb&&this.uv()):(this.I=!0,this.pe()&&(2===a?this.i.uu():3===a&&this.i.Oq()))};
g.k.NR=function(a){a?this.FJ(1):(this.u=null,this.I=!1)};
g.k.Jv=function(){return 1!==this.videoData.autonavState};
g.k.Af=function(a){return(910>a.width||459>a.height)&&!this.IA(a)&&!(400>=a.width||360>=a.height)};
g.k.IA=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.pe=function(){return this.rb&&g.WM(this.player)&&this.Jv()&&!this.u};
var QXa=[1,3,2,4];g.v(Z5,U5);Z5.prototype.Ia=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.pj;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.v($5,g.V);$5.prototype.select=function(){(this.api.jk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.dw||void 0)||this.api.L("web_player_endscreen_double_log_fix_killswitch"))&&this.api.vb(this.element)};
$5.prototype.onClick=function(a){g.HN(a,this.api,this.j,this.suggestion.sessionData||void 0)&&this.select()};
$5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.It(a)||(this.select(),g.Ht(a))}};
$5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.j=a.C?!1:b.i};g.v(a6,U5);g.k=a6.prototype;g.k.create=function(){U5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Ll();this.j.S(this.player,"appresize",this.Ll);this.j.S(this.player,"onVideoAreaChange",this.Ll);this.j.S(this.player,"videodatachange",this.onVideoDataChange);this.j.S(this.player,"autonavchange",this.pD);this.j.S(this.player,"autonavcancel",this.OR);a=this.videoData.autonavState;a!==this.N&&this.pD(a);this.j.S(this.element,"transitionend",this.YX)};
g.k.destroy=function(){g.Fw(this.j);g.df(this.stills);this.stills=[];U5.prototype.destroy.call(this);g.iq(this.element,"ytp-show-tiles");this.I.stop();this.N=this.videoData.autonavState};
g.k.Jv=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){U5.prototype.show.call(this);g.iq(this.element,"ytp-show-tiles");this.player.U().isMobile?g.bq(this.I):this.I.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.QM(this.player,!1);b6(this)?(c6(this),2===this.videoData.autonavState?this.player.U().L("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.uu():3===this.videoData.autonavState&&this.i.Oq()):(g.QM(this.player,!0),c6(this))};
g.k.hide=function(){U5.prototype.hide.call(this);this.i.Oq();c6(this)};
g.k.YX=function(a){g.Dt(a)===this.element&&this.Ll()};
g.k.Ll=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=this.G.Fj(!0,this.G.isFullscreen()),b=g.LM(this.G);b&&(b=b.Ye()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,u=e<=h-2&&n>=p*m;if((p+
1)/r*d/c>c/(p/(r+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=r*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.On(a,m,n);g.yn(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.bz(this.videoData.suggestions[0]);this.i instanceof Q5&&T5(this.i);g.N(this.element,"ytp-endscreen-takeover",b6(this));c6(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.eh(p+this.u,l),0!==r){t=this.stills[c];t||(t=new $5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-u-4,z=Math.floor(m*(f+r)/b)-x-4;g.Kn(t.element,x,u);g.On(t.element,z,y);g.yn(t.element,"transitionDelay",(h+f)/20+"s");g.N(t.element,"ytp-videowall-still-mini",1===r);g.N(t.element,"ytp-videowall-still-large",
2<r);r=t;p=this.videoData.suggestions[p];r.suggestion!==p&&(r.suggestion=p,t=r.api.U(),u=g.gq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",N5(r,p,u),g.YD(t)&&(t=p.al(),t=g.Ij(t,g.PL("emb_rel_end")),r.La("url",t)),(p=(p=p.sessionData)&&p.itct)&&r.api.bk(r.element,p));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Vh(e.element),g.cf(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.videoData=a,this.Ll())};
g.k.PR=function(){this.u+=this.stills.length;this.Ll()};
g.k.QR=function(){this.u-=this.stills.length;this.Ll()};
g.k.HM=function(){return this.i.Mh()};
g.k.pD=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.dn(),this.rb&&this.Ll()):(this.C=!0,this.rb&&b6(this)&&(2===a?this.i.uu():3===a&&this.i.Oq()))};
g.k.OR=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.bb(this.stills[a].element,!0);this.pD(1)}else this.B=null,this.C=!1;this.Ll()};
g.k.pe=function(){return this.rb&&b6(this)};g.v(d6,g.iN);g.k=d6.prototype;g.k.ir=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!NXa(this.player)||b;var c=a.Ie||g.iE(a.u),d=this.player.mw();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.pe=function(){return this.endScreen.pe()};
g.k.yU=function(){return this.pe()?this.endScreen.HM():!1};
g.k.ra=function(){this.player.gf("endscreen");g.iN.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.LM;if(b&&b.videoId){var c=this.player.sb().Hd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.YJ?a=!1:(this.player.jk(b.videoId,void 0,void 0,!0,!0,b),c&&c.RA("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.iN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.iN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.ir()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){PXa(this);this.u&&OXa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new X5(this.player):this.endScreen=new a6(this.player),g.I(this,this.endScreen),g.VM(this.player,this.endScreen.element,4))};g.hN("endscreen",d6);})(_yt_player);
